In [13]:
import numpy as np
import random
import pandas as pd


In [5]:
arr1=[]
for i in range(0,3):
    list=[]
    for j in range(0,2):
        list.append(random.randint(0,100))
    arr1.append(list)
array1=np.array(arr1)
print(array1)

[[10 22]
 [ 1 70]
 [48 90]]


In [6]:
arr2=[]
for i in range(0,2):
    list=[]
    for j in range(0,3):
        list.append(random.randint(0,100))
    arr2.append(list)
array2=np.array(arr2)
print(array2)

[[92 22 50]
 [20 64 43]]


In [7]:
multiplies=np.matmul(array1,array2)
multiplies

array([[1360, 1628, 1446],
       [1492, 4502, 3060],
       [6216, 6816, 6270]])

In [8]:
# perform element wise matrix multiplication
res = [[0 for x in range(len(array1))] for y in range(len(array2[0]))]

for i in range(len(array1)): 
  for j in range(len(array2[0])): 
    for k in range(len(array2)): 
      res[i][j] += array1[i][k] * array2[k][j]
 
print (res)

[[1360, 1628, 1446], [1492, 4502, 3060], [6216, 6816, 6270]]


In [9]:
# mean of first matrix
mean = np.mean(array1)
print(mean)

40.166666666666664


In [11]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [14]:

main_data = pd.read_csv("/content/drive/MyDrive/L2/Datasets/mtcars.csv")


In [15]:
del main_data['model']
# meancenter
meancenter = main_data.apply(lambda e: e - e.mean())
print(meancenter.head())

        mpg     cyl        disp       hp  ...      vs       am    gear    carb
0  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
1  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
2  2.709375 -2.1875 -122.721875 -53.6875  ...  0.5625  0.59375  0.3125 -1.8125
3  1.309375 -0.1875   27.278125 -36.6875  ...  0.5625 -0.40625 -0.6875 -1.8125
4 -1.390625  1.8125  129.278125  28.3125  ... -0.4375 -0.40625 -0.6875 -0.8125

[5 rows x 11 columns]
