In [1]:
from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
import numpy as np

In [3]:
#Load dataset
digits = datasets.load_digits()
print(digits)

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]]), 'target': array([0, 1, 2, ..., 8, 9, 8]), 'target_names': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 'images': array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ..., 15.,  5.,  0.],
        [ 0.,  3., 15., ..., 11.,  8.,  0.],
        ...,
        [ 0.,  4., 11., ..., 12.,  7.,  0.],
        [ 0.,  2., 14., ..., 12.,  0.,  0.],
        [ 0.,  0.,  6., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
        [ 0.,  0.,  0., ...,  9.,  0.,  0.],
        [ 0.,  0.,  3., ...,  6.,  0.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.]],

       [[ 0.,  0.,  0., ..., 12.,  0

In [4]:
print(digits.data.shape)
print(digits.target.shape)

(1797, 64)
(1797,)


In [5]:
from sklearn.model_selection import train_test_split


In [6]:
X=digits.data
Y=digits.target
#split data set into train and test sets
X_train, X_test, y_train, y_test = train_test_split( 
    X, Y, test_size = 0.35, random_state = 100)


In [7]:
#Create a Decision Tree Classifier (using Gini)
clf_gini = DecisionTreeClassifier(criterion = "gini",
            random_state = 26,max_depth=7, min_samples_leaf=26)

clf_gini.fit(X_train, y_train)


DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=7, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=26, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=26, splitter='best')

In [8]:
# Predict the classes of test data
y_pred = clf_gini.predict(X_test)
print("Predicted values:")
print(y_pred)


Predicted values:
[9 9 0 2 4 5 7 4 9 2 4 5 7 5 9 6 1 9 5 6 8 7 6 6 6 4 0 2 4 3 0 9 3 9 9 5 3
 6 3 6 1 1 5 2 0 4 8 9 7 4 9 5 5 1 4 8 9 7 3 9 6 2 5 4 2 6 3 6 6 6 8 1 6 0
 6 6 2 9 0 2 2 3 3 1 1 4 8 5 0 1 1 7 0 0 8 1 4 0 7 5 1 0 9 3 4 5 7 1 1 5 5
 2 1 3 2 0 9 4 7 3 2 1 3 6 0 7 0 7 5 0 7 6 0 2 8 6 0 7 4 2 9 5 0 8 9 0 8 0
 3 6 8 4 4 8 8 9 0 0 1 2 2 7 9 9 1 9 1 5 3 4 2 0 6 9 9 1 0 0 7 4 4 1 3 9 5
 3 4 9 2 2 2 1 4 7 2 7 1 0 1 3 8 6 9 9 0 3 1 9 3 8 0 6 8 6 2 9 2 2 6 6 1 4
 1 2 3 0 7 1 7 2 1 1 0 9 0 5 0 7 7 7 0 2 7 0 8 2 2 7 3 4 0 2 1 5 1 2 4 7 0
 5 9 3 9 2 2 0 4 7 9 4 0 2 1 8 7 0 9 1 0 7 9 6 0 5 0 9 6 7 7 1 2 4 1 0 1 1
 9 6 1 1 7 9 9 7 8 2 1 0 2 5 9 6 9 3 9 0 7 3 0 7 8 4 5 4 4 4 8 4 0 6 6 7 5
 4 5 1 6 2 4 3 9 7 9 4 7 8 1 9 2 5 4 6 6 3 4 4 7 6 7 3 3 4 4 1 6 1 2 0 8 3
 5 8 4 1 6 4 8 7 7 4 5 8 9 4 4 3 2 7 7 3 4 9 3 5 7 4 2 9 1 8 8 5 1 8 0 8 2
 1 6 2 5 1 4 9 2 4 9 2 4 0 7 7 7 2 4 0 9 3 8 0 9 9 8 4 0 4 0 0 1 4 1 4 0 8
 6 6 4 4 9 4 3 6 1 1 1 9 7 1 1 5 1 7 7 0 5 9 1 9 6 3 0 1 5 2 9 1 0 0 7 9 3
 6 0 1 

In [9]:
from sklearn import metrics
print("Confusion Matrix: ",
        metrics.confusion_matrix(y_test, y_pred))
print ("Accuracy : ",
    metrics.accuracy_score(y_test,y_pred)*100)
print("Report : ",
    metrics.classification_report(y_test, y_pred))

Confusion Matrix:  [[66  1  1  0  0  0  0  0  1  1]
 [ 0 42  2  0  3  0  0  2  2 10]
 [ 1  9 49  5  2  0  3  0  0  0]
 [ 0  0  6 38  0  0  0  6  3  6]
 [ 2 13  0  0 52  0  0  0  0  2]
 [ 3  1  0  0  1 47  0  0  0 12]
 [ 3  4  0  0  5  0 52  0  0  0]
 [ 0  1  0  0  4  0  0 50  0  1]
 [ 1  5  3  1  3  0  0  2 32  6]
 [ 1  0  4  3  0  0  0  8  2 46]]
Accuracy :  75.3577106518283
Report :                precision    recall  f1-score   support

           0       0.86      0.94      0.90        70
           1       0.55      0.69      0.61        61
           2       0.75      0.71      0.73        69
           3       0.81      0.64      0.72        59
           4       0.74      0.75      0.75        69
           5       1.00      0.73      0.85        64
           6       0.95      0.81      0.87        64
           7       0.74      0.89      0.81        56
           8       0.80      0.60      0.69        53
           9       0.55      0.72      0.62        64

    accuracy   